name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.61.191.211
          port: 22
          username: laracasts
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd www
            git pull origin main
            composer update --ignore-platform-reqs
            php artisan migrate
            npm install
            npm run build
            sudo service php8.2-fpm reload
