name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 16.170.129.205
          port: 22
          username: laracasts
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; git pull origin main; composer install; php artisan migrate; npm install; npm run build; sudo service php8.2-fpm reload"
